import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const pluginContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

/**
 * The portable, read-only public map viewer (src/view/customScript.ts) — zero Obsidian dependency,
 * zero external imports, so it's a single drop-in file: this plugin's only job is to build it here;
 * getting it into the site (e.g. via that site's generic "custom scripts" mechanism — a
 * default-exported function, called client-side after the page mounts) is the site-export plugin's
 * concern, not this one's. It scans the page for ```map``` code blocks and fetches/mounts each
 * one's `<basename>.json` (see src/platform/publishPublicSnapshot.ts).
 */
const viewerContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/view/customScript.ts"],
	bundle: true,
	format: "esm",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "map-manager-viewer.js",
	minify: prod,
});

if (prod) {
	await pluginContext.rebuild();
	await viewerContext.rebuild();
	process.exit(0);
} else {
	await pluginContext.watch();
	await viewerContext.watch();
}
